CREATE TYPE "UserRole" AS ENUM ('MANAGER', 'SUBSTITUTE', 'WORKER');
CREATE TYPE "TicketStatus" AS ENUM ('ENTERED', 'DERIVED', 'IN_PROGRESS', 'PENDING_INFORMATION', 'FINISHED', 'CLOSED');
CREATE TYPE "Priority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE "InputChannel" AS ENUM ('IN_PERSON', 'EMAIL');
CREATE TYPE "StorageType" AS ENUM ('LOCAL', 'GOOGLE_DRIVE');
CREATE TYPE "TicketHistoryAction" AS ENUM ('CREATED', 'UPDATED', 'ASSIGNED', 'DERIVED', 'STATUS_CHANGED', 'COMMENT_ADDED', 'ATTACHMENT_ADDED', 'SLA_UPDATED', 'DUE_DATE_UPDATED', 'FINISHED', 'CLOSED', 'REOPENED');
CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TicketType" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "slaDays" INTEGER NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TicketType_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Ticket" ("id" TEXT NOT NULL, "correlative" SERIAL NOT NULL, "ticketCode" TEXT, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "priority" "Priority" NOT NULL, "status" "TicketStatus" NOT NULL DEFAULT 'ENTERED', "inputChannel" "InputChannel" NOT NULL, "ticketTypeId" TEXT NOT NULL, "requesterName" TEXT, "requesterEmail" TEXT, "requesterPhone" TEXT, "assignedToId" TEXT NOT NULL, "createdById" TEXT NOT NULL, "closedById" TEXT, "appliedSlaDays" INTEGER NOT NULL, "dueDate" TIMESTAMP(3) NOT NULL, "finishedAt" TIMESTAMP(3), "closedAt" TIMESTAMP(3), "enabled" BOOLEAN NOT NULL DEFAULT true, "deleted" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Ticket_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TicketDerivation" ("id" TEXT NOT NULL, "ticketId" TEXT NOT NULL, "fromUserId" TEXT NOT NULL, "toUserId" TEXT NOT NULL, "performedById" TEXT NOT NULL, "observation" TEXT, "previousStatus" "TicketStatus" NOT NULL, "newStatus" "TicketStatus" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TicketDerivation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TicketHistory" ("id" TEXT NOT NULL, "ticketId" TEXT NOT NULL, "userId" TEXT NOT NULL, "action" "TicketHistoryAction" NOT NULL, "previousStatus" "TicketStatus", "newStatus" "TicketStatus", "previousAssigneeId" TEXT, "newAssigneeId" TEXT, "details" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TicketHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TicketComment" ("id" TEXT NOT NULL, "ticketId" TEXT NOT NULL, "userId" TEXT NOT NULL, "content" TEXT NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TicketComment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TicketAttachment" ("id" TEXT NOT NULL, "ticketId" TEXT NOT NULL, "uploadedById" TEXT NOT NULL, "fileName" TEXT NOT NULL, "originalName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" INTEGER NOT NULL, "storageType" "StorageType" NOT NULL DEFAULT 'LOCAL', "localPath" TEXT, "driveFileId" TEXT, "url" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "TicketAttachment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "TicketType_name_key" ON "TicketType"("name");
CREATE UNIQUE INDEX "Ticket_correlative_key" ON "Ticket"("correlative");
CREATE UNIQUE INDEX "Ticket_ticketCode_key" ON "Ticket"("ticketCode");
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_ticketTypeId_fkey" FOREIGN KEY ("ticketTypeId") REFERENCES "TicketType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_closedById_fkey" FOREIGN KEY ("closedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TicketDerivation" ADD CONSTRAINT "TicketDerivation_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketDerivation" ADD CONSTRAINT "TicketDerivation_fromUserId_fkey" FOREIGN KEY ("fromUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketDerivation" ADD CONSTRAINT "TicketDerivation_toUserId_fkey" FOREIGN KEY ("toUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketDerivation" ADD CONSTRAINT "TicketDerivation_performedById_fkey" FOREIGN KEY ("performedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketHistory" ADD CONSTRAINT "TicketHistory_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketHistory" ADD CONSTRAINT "TicketHistory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketComment" ADD CONSTRAINT "TicketComment_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketComment" ADD CONSTRAINT "TicketComment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketAttachment" ADD CONSTRAINT "TicketAttachment_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketAttachment" ADD CONSTRAINT "TicketAttachment_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
